{"tag": "function", "depth": 3, "time": 1647340393.2741213, "data": {"name": "_cv_match", "call_args": {"self": {"filename": "tpl1647340378854.png", "_filepath": null, "threshold": 0.7, "target_pos": 5, "record_pos": [0.002, 0.583], "resolution": [900, 1600], "rgb": false, "scale_max": 800, "scale_step": 0.005, "__class__": "Template"}, "screen": "array([[[ 59, 113,  70],\n        [ 62, 116,  73],\n        [ 68, 121,  78],\n        ...,\n        [  0,   0,   0],\n        [  0,   0,   0],\n        [  0,   0,   0]],\n\n       [[ 48, 101,  58],\n        [ 51, 104,  61],\n        [ 54, 107,  64],\n        ...,\n        [  0,   0,   0],\n        [  0,   0,   0],\n        [  0,   0,   0]],\n\n       [[ 41,  91,  49],\n        [ 42,  92,  50],\n        [ 44,  94,  52],\n        ...,\n        [  0,   0,   0],\n        [  0,   0,   0],\n        [  0,   0,   0]],\n\n       ...,\n\n       [[254, 247, 230],\n        [254, 247, 230],\n        [255, 248, 231],\n        ...,\n        [  0,   0,   0],\n        [  0,   0,   0],\n        [  0,   0,   0]],\n\n       [[254, 247, 230],\n        [254, 247, 230],\n        [255, 248, 231],\n        ...,\n        [  0,   0,   0],\n        [  0,   0,   0],\n        [  0,   0,   0]],\n\n       [[254, 247, 230],\n        [254, 247, 230],\n        [255, 248, 231],\n        ...,\n        [  0,   0,   0],\n        [  0,   0,   0],\n        [  0,   0,   0]]], dtype=uint8)"}, "start_time": 1647340393.2731197, "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\core\\cv.py\", line 169, in _cv_match\n    ori_image = self._imread()\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\core\\cv.py\", line 202, in _imread\n    return aircv.imread(self.filepath)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\aircv\\aircv.py\", line 15, in imread\n    raise FileNotExistError(\"File not exist: %s\" % filename)\nairtest.aircv.error.FileNotExistError: File not exist: tpl1647340378854.png\n", "end_time": 1647340393.2741213}}
{"tag": "function", "depth": 2, "time": 1647340393.275124, "data": {"name": "loop_find", "call_args": {"query": {"filename": "tpl1647340378854.png", "_filepath": null, "threshold": 0.7, "target_pos": 5, "record_pos": [0.002, 0.583], "resolution": [900, 1600], "rgb": false, "scale_max": 800, "scale_step": 0.005, "__class__": "Template"}, "timeout": 20, "threshold": null, "interval": 0.5, "intervalfunc": null}, "start_time": 1647340390.2876835, "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\core\\cv.py\", line 69, in loop_find\n    match_pos = query.match_in(screen)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\core\\cv.py\", line 154, in match_in\n    match_result = self._cv_match(screen)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\core\\cv.py\", line 169, in _cv_match\n    ori_image = self._imread()\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\core\\cv.py\", line 202, in _imread\n    return aircv.imread(self.filepath)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\aircv\\aircv.py\", line 15, in imread\n    raise FileNotExistError(\"File not exist: %s\" % filename)\nairtest.aircv.error.FileNotExistError: File not exist: tpl1647340378854.png\n", "end_time": 1647340393.275124}}
{"tag": "function", "depth": 1, "time": 1647340393.2756252, "data": {"name": "touch", "call_args": {"v": {"filename": "tpl1647340378854.png", "_filepath": null, "threshold": 0.7, "target_pos": 5, "record_pos": [0.002, 0.583], "resolution": [900, 1600], "rgb": false, "scale_max": 800, "scale_step": 0.005, "__class__": "Template"}, "kwargs": {}, "times": 1}, "start_time": 1647340390.2876835, "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\core\\api.py\", line 352, in touch\n    pos = loop_find(v, timeout=ST.FIND_TIMEOUT)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\core\\cv.py\", line 69, in loop_find\n    match_pos = query.match_in(screen)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\core\\cv.py\", line 154, in match_in\n    match_result = self._cv_match(screen)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\core\\cv.py\", line 169, in _cv_match\n    ori_image = self._imread()\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\core\\cv.py\", line 202, in _imread\n    return aircv.imread(self.filepath)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\airtest\\aircv\\aircv.py\", line 15, in imread\n    raise FileNotExistError(\"File not exist: %s\" % filename)\nairtest.aircv.error.FileNotExistError: File not exist: tpl1647340378854.png\n", "end_time": 1647340393.2756252}}
